In [1]:
import numpy as np

In [2]:
myList = [1,2,3,4,5]

In [7]:
a = np.array(myList)
a

array([1, 2, 3, 4, 5])

In [4]:
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
myMatrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
b = np.array(myMatrix)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
b.ndim

2

In [22]:
b.size

9

In [10]:
print('The size of array: ',b.size)

The size of array:  9


In [52]:
myMat3 = [
    [
        [1,2,3],
        [4,5,6],
        [7,8,'test']
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
    [
        [10,11,12],
        [13,14,15],
        [16,17,18]
    ],
]

In [53]:
mat3d=np.array(myMat3)

In [54]:
mat3d.ndim

3

In [55]:
mat3d.size

27

In [51]:
mat3d.dtype

dtype('<U11')

In [91]:
myMat4 = [
    [
        [
            [
                [1,2,3],
                [4,5,6],
                [7,8,9]
            ],
            [
                [1,2,3],
                [1,2,3],
                [1,2,3],
            ],
            [
                [1,2,3],
                [4,5,6],
                [7,8,9],
            ],
            [
                [1,2,3],
                [1,2,3],
                [1,2,3],
            ],
            [
                [1,2,3],
                [1,2,3],
                [1,2,3],
            ]
        ]
    ]
]

In [92]:
mat4d = np.array(myMat4)

In [93]:
mat4d.ndim

5

In [94]:
mat4d.shape

(1, 1, 5, 3, 3)

In [74]:
b.shape

(3, 3)

In [75]:
a.ndim

1

In [76]:
a.size

5

In [77]:
a.shape

(5,)

In [95]:
c = np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])

In [96]:
c.ndim

4

In [97]:
c.shape

(1, 1, 2, 5)

In [103]:
#arange

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [104]:
np.arange(0,15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [107]:
np.arange(0,11,2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [108]:
#reshape

In [138]:
np.arange(2,25).reshape(5,5,2,1,1,1)

ValueError: cannot reshape array of size 23 into shape (5,5,2,1,1,1)

In [120]:
ar = np.arange(1,16)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [128]:
np.resize(ar,(5,10))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15,  1,  2,  3,  4,  5]])

In [140]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [142]:
np.zeros(3)

array([0., 0., 0.])

In [147]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [148]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [149]:
np.ones((5,5,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [174]:
#linespace
np.linspace(0,0.1,num=1000,retstep=True)

(array([0.        , 0.0001001 , 0.0002002 , 0.0003003 , 0.0004004 ,
        0.0005005 , 0.0006006 , 0.0007007 , 0.0008008 , 0.0009009 ,
        0.001001  , 0.0011011 , 0.0012012 , 0.0013013 , 0.0014014 ,
        0.0015015 , 0.0016016 , 0.0017017 , 0.0018018 , 0.0019019 ,
        0.002002  , 0.0021021 , 0.0022022 , 0.0023023 , 0.0024024 ,
        0.0025025 , 0.0026026 , 0.0027027 , 0.0028028 , 0.0029029 ,
        0.003003  , 0.0031031 , 0.0032032 , 0.0033033 , 0.0034034 ,
        0.0035035 , 0.0036036 , 0.0037037 , 0.0038038 , 0.0039039 ,
        0.004004  , 0.0041041 , 0.0042042 , 0.0043043 , 0.0044044 ,
        0.0045045 , 0.0046046 , 0.0047047 , 0.0048048 , 0.0049049 ,
        0.00500501, 0.00510511, 0.00520521, 0.00530531, 0.00540541,
        0.00550551, 0.00560561, 0.00570571, 0.00580581, 0.00590591,
        0.00600601, 0.00610611, 0.00620621, 0.00630631, 0.00640641,
        0.00650651, 0.00660661, 0.00670671, 0.00680681, 0.00690691,
        0.00700701, 0.00710711, 0.00720721, 0.00

In [173]:
np.linspace(1,200,10,retstep=True)

(array([  1.        ,  23.11111111,  45.22222222,  67.33333333,
         89.44444444, 111.55555556, 133.66666667, 155.77777778,
        177.88888889, 200.        ]),
 22.11111111111111)

In [175]:
# eye

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [176]:
#Random

np.random.rand(4)

array([0.15296813, 0.56509877, 0.3762928 , 0.62701571])

In [181]:
np.random.rand(5,3,3)

array([[[0.68493149, 0.63474889, 0.4201253 ],
        [0.82673605, 0.89815772, 0.99239508],
        [0.69479451, 0.17395328, 0.58235329]],

       [[0.42796478, 0.8557434 , 0.18865925],
        [0.11830206, 0.77234202, 0.86704078],
        [0.53472249, 0.42341848, 0.78930877]],

       [[0.08217207, 0.43913953, 0.21286172],
        [0.21342401, 0.73631682, 0.96118195],
        [0.52993873, 0.68780298, 0.86681207]],

       [[0.74018511, 0.51414555, 0.0104676 ],
        [0.90471734, 0.73010096, 0.79675143],
        [0.21637449, 0.91664076, 0.6640616 ]],

       [[0.15473613, 0.15799396, 0.14639983],
        [0.53803482, 0.91255715, 0.02319213],
        [0.38498062, 0.68604399, 0.43233263]]])

In [178]:
np.random.rand(3,3)

array([[0.9552026 , 0.32621449, 0.1760204 ],
       [0.93368643, 0.52629501, 0.15792612],
       [0.53826811, 0.21456014, 0.11800258]])

In [184]:
np.random.randn(20)

array([ 0.92667869, -0.51840793, -2.12696912, -0.07020076,  1.68028165,
        0.02795781, -0.05148794,  1.66433284, -0.31399827,  1.22904145,
       -0.41466278,  0.210464  ,  0.40545059,  0.65667349, -1.3982369 ,
       -1.84624592, -0.95065337, -0.8574186 ,  0.26267382, -1.05191356])

In [185]:
np.random.randn(3,3)

array([[ 0.80031267,  0.77634203,  0.07866875],
       [-1.02335525,  0.33466194,  0.24774052],
       [-0.23045276, -0.04682738,  0.56469641]])

In [611]:
# randint

np.random.randint(1,100)

48

In [713]:
np.random.randint(1,5,3)

array([3, 3, 3])

In [716]:
arr1 = np.arange(20)
arr2 = np.random.randint(0,100,10)

In [717]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [718]:
arr2

array([78, 18, 41, 42, 28, 20, 30, 35, 10,  8])

In [719]:
arr1.max()

19

In [720]:
arr1.argmax()

19

In [723]:
arr2.max()

78

In [724]:
arr2.argmax() #index number of maximum element

0

In [725]:
arr1.min()

0

In [726]:
arr2.min()

8

In [728]:
arr1.argmin()

0

In [729]:
arr2.argmin()

9