In [1]:
import numpy as np

In [4]:
arr = np.arange(0,21)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [6]:
arr[10]

10

In [7]:
arr[1:11]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[1:20:2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

# Broadcasting
* Numpy arrays differ from normal pythhon lists because of their ability to braodcase

In [9]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [12]:
arr[:] = 100
arr[:]

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100])

In [13]:
arr1 = np.array([1,2,3])

In [14]:
arr1

array([1, 2, 3])

In [15]:
arr2 = np.array([4,5,6])

In [16]:
arr2

array([4, 5, 6])

In [17]:
arr1 - arr2

array([-3, -3, -3])

In [18]:
arr1 + arr2

array([5, 7, 9])

In [19]:
arr1 * arr2

array([ 4, 10, 18])

In [20]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [21]:
arr1 // arr2

array([0, 0, 0], dtype=int32)

In [22]:
arr1 % arr2

array([1, 2, 3], dtype=int32)

In [23]:
arr2 % arr1

array([0, 1, 0], dtype=int32)

In [25]:
l1 = [3,2,1]
l2 = [1,2,3]

print(l1+l2)

[3, 2, 1, 1, 2, 3]


In [26]:
# filtering condition
# it will return index number/s of satisfied condition
arr = np.array([1,2,1010,4,8,18,7])

In [27]:
np.where(arr>100)

(array([2], dtype=int64),)

In [28]:
np.where(arr<100)

(array([0, 1, 3, 4, 5, 6], dtype=int64),)

In [76]:
arr > 10

array([False, False,  True,  True,  True,  True,  True])

In [30]:
arr[3:] = 100

In [32]:
#copying with assigment operation will take reference, 
#means everytime values are going to change if we change on any of the array
arr1 = arr

In [33]:
arr1[3:] = 500

In [34]:
arr

array([   1,    2, 1010,  500,  500,  500,  500])

In [35]:
arr1

array([   1,    2, 1010,  500,  500,  500,  500])

In [36]:
# it will just copy and won't take any reference

arr2 = arr1.copy()

In [38]:
arr2[3:] = 100

In [39]:
arr2

array([   1,    2, 1010,  100,  100,  100,  100])

In [40]:
arr1

array([   1,    2, 1010,  500,  500,  500,  500])

# Indexing a 2D Array (Matrices)

In [41]:
arr2d = np.array(([5,10,5],[20,25,30],[35,40,45]))

arr2d

array([[ 5, 10,  5],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr2d[1]

array([20, 25, 30])

In [43]:
arr2d[1][0]

20

In [44]:
arr2d[1,0]

20

In [48]:
# 2D array slicing

# Shape (2,2) from top right corner

arr2d[:2,1:]

array([[10,  5],
       [25, 30]])

In [66]:
arr2d[0:,1:2]

array([[10],
       [25],
       [40]])

# Univarsal Laws

In [86]:
arr = np.arange(0,10)

In [87]:
arr2d / arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [88]:
arr / arr

C:\Users\Ovesh-pc\AppData\Local\Temp/ipykernel_10616/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [89]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

# Univarsa; Array Funcitons

In [91]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [92]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [93]:
np.max(arr)

9

In [94]:
np.min(arr)

0

In [95]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [96]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [97]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [99]:
np.log(arr)

C:\Users\Ovesh-pc\AppData\Local\Temp/ipykernel_10616/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [100]:
## conversion from degree to radian

d=np.arange(0,120,30).reshape(2,2)
d

array([[ 0, 30],
       [60, 90]])

In [102]:
rad = d * np.pi/180
rad

array([[0.        , 0.52359878],
       [1.04719755, 1.57079633]])

In [106]:
np.sin(rad)

array([[0.       , 0.5      ],
       [0.8660254, 1.       ]])

In [107]:
np.sin(d)

array([[ 0.        , -0.98803162],
       [-0.30481062,  0.89399666]])

In [114]:
cosec = 1/np.sin(rad)

C:\Users\Ovesh-pc\AppData\Local\Temp/ipykernel_10616/3944677956.py:1: RuntimeWarning: divide by zero encountered in true_divide
  cosec = 1/np.sin(rad)


In [115]:
cosec

array([[       inf, 2.        ],
       [1.15470054, 1.        ]])